# Generated by Django 3.2.25 on 2026-02-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
    ]
