# Generated by Django 3.2.25 on 2026-02-25 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0003_auto_20260225_1116'),
        ('File', '0002_alter_document_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approval',
            field=models.ManyToManyField(blank=True, related_name='document_approval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='department_viewer',
            field=models.ManyToManyField(blank=True, related_name='document_department_viewer', to='User.Department'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='posted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='public_viewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_source', to='User.department'),
        ),
        migrations.AddField(
            model_name='document',
            name='specific_viewer',
            field=models.ManyToManyField(blank=True, related_name='document_specific_viewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='time_posted',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
