# Generated by Django 3.2.25 on 2026-03-02 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0003_auto_20260225_1116'),
        ('File', '0003_auto_20260225_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('content_text', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('revision_number', models.IntegerField(default=1)),
                ('board_resolution_number', models.CharField(blank=True, max_length=200, null=True)),
                ('date_issued', models.DateField()),
                ('related_board_resolution_number', models.CharField(blank=True, max_length=200, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('time_posted', models.TimeField(blank=True, null=True)),
                ('approval_status', models.CharField(default='Pending', max_length=50)),
                ('public_viewer', models.BooleanField(default=False)),
                ('approval', models.ManyToManyField(blank=True, related_name='document_file_approval', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_file_department', to='User.department')),
                ('department_viewer', models.ManyToManyField(blank=True, related_name='document_file_department_viewer', to='User.Department')),
                ('specific_viewer', models.ManyToManyField(blank=True, related_name='document_file_specific_viewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
