# Generated by Django 3.2.25 on 2026-03-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0004_documentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
    ]
