# Generated by Django 3.2.25 on 2026-03-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0006_alter_documentfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
