# Generated by Django 3.2.25 on 2026-04-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0007_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_posted', models.DateField()),
                ('posted_by', models.CharField(max_length=100)),
            ],
        ),
    ]
