# Generated by Django 3.2.25 on 2026-05-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0008_documenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('function', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
