# Generated by Django 3.2.25 on 2026-05-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0009_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='subject',
        ),
    ]
