# Generated by Django 3.2.25 on 2026-05-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0010_auto_20260506_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
