# Generated by Django 3.2.25 on 2026-05-06 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_userprofile_admin_uploader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('File', '0011_delete_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=200)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('content_text', models.TextField(blank=True)),
                ('scanned', models.BooleanField(default=False)),
                ('revision_number', models.IntegerField(default=1)),
                ('board_resolution_number', models.CharField(blank=True, max_length=200, null=True)),
                ('date_issued', models.DateField()),
                ('related_board_resolution_number', models.CharField(blank=True, max_length=200, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('time_posted', models.TimeField(blank=True, null=True)),
                ('approval_status', models.CharField(default='Pending', max_length=50)),
                ('public_viewer', models.BooleanField(default=False)),
                ('approval', models.ManyToManyField(blank=True, related_name='document_file_approval_activity', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_file_department_activity', to='User.department')),
                ('department_viewer', models.ManyToManyField(blank=True, related_name='document_file_department_viewer_activity', to='User.Department')),
                ('specific_viewer', models.ManyToManyField(blank=True, related_name='document_file_specific_viewer_activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
