# Generated by Django 3.2.25 on 2026-05-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0012_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='file_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
