# Generated by Django 3.2.25 on 2026-05-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_group_groupemail'),
        ('File', '0013_activity_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='group_viewer',
            field=models.ManyToManyField(blank=True, related_name='document_groups', to='User.Group'),
        ),
    ]
