# Generated by Django 3.2.25 on 2026-06-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_delete_groupemail'),
        ('File', '0014_documentfile_group_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='group_viewer',
            field=models.ManyToManyField(blank=True, related_name='document_file_group_viewer_activity', to='User.MainGroup'),
        ),
    ]
