#version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app:consistent
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    ports:
      - "6379:6379"
  #celery:
  #  build: .
  #  command: celery -A time_tracking_be.celery worker -l info
  #  volumes:
  #    - .:/app:consistent
  #  depends_on:
  #    - redis
  #    - db
  #celery_beat:
  #  build: .
  #  command: celery -A time_tracking_be beat --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #  volumes:
  #    - .:/app:consistent
  #  depends_on:
  #    - redis
  #    - db