# Generated by Django 3.2.25 on 2026-02-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=500)),
                ('content_text', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('scanned', models.BooleanField()),
            ],
        ),
    ]
