# Generated by Django 3.2.25 on 2025-07-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('birthday', models.DateField()),
                ('citizenship', models.CharField(blank=True, max_length=150, null=True)),
                ('religion', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=150, null=True)),
                ('rfid_number', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
