# Generated by Django 3.2.25 on 2025-07-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Student',
        ),
    ]
