# Generated by Django 3.2.25 on 2025-07-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_rename_client_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
