# Generated by Django 3.2.25 on 2025-07-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_student_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='posted_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='time_posted',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
