# Generated by Django 3.2.25 on 2025-07-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
