# Generated by Django 3.2.25 on 2025-08-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_auto_20250818_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
