# Generated by Django 3.2.25 on 2025-07-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='branch_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_number',
        ),
    ]
