# Generated by Django 3.2.25 on 2026-03-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20260225_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='admin_access',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uploader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_page',
            field=models.BooleanField(default=False),
        ),
    ]
