# Generated by Django 3.2.25 on 2026-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20260304_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
