# Generated by Django 3.2.25 on 2026-05-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_userprofile_employee_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='employee_number',
            new_name='employee_id',
        ),
    ]
