# Generated by Django 3.2.25 on 2026-05-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_rename_employee_number_userprofile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_helper',
            field=models.BooleanField(default=False),
        ),
    ]
