# Generated by Django 3.2.25 on 2026-05-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_userprofile_ai_helper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ai_helper',
        ),
    ]
