# Generated by Django 3.2.25 on 2026-05-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_userprofile_ai_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_helper',
            field=models.BooleanField(default=False),
        ),
    ]
