# Generated by Django 3.2.25 on 2026-05-05 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_userprofile_ai_helper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='admin_access',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='covid_leave',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_panel_calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='endorser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='forced_leave',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lwop',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='magna_carta_leave',
            field=models.FloatField(default=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manual_in_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='maternity_leave',
            field=models.FloatField(default=105),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paternity_leave',
            field=models.FloatField(default=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permanency_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='salary_per_day',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='salary_per_month',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='schedule_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='schedule_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='service_incentive_leave',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sick_leave',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='solo_parent_leave',
            field=models.FloatField(default=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vacation_leave',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vawc_leave',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.level'),
        ),
    ]
