# Generated by Django 3.2.25 on 2026-05-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20260505_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ai_helper',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_page',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
