# Generated by Django 3.2.25 on 2026-05-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20260505_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_helper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uploader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_page',
            field=models.BooleanField(default=False),
        ),
    ]
