# Generated by Django 3.2.25 on 2026-05-05 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20260505_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='admin_access',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='covid_leave',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department_attendance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='employee_panel_calendar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='endorser',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='forced_leave',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lwop',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='magna_carta_leave',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='manual_in_out',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='maternity_leave',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paternity_leave',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='permanency_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='salary_per_day',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='salary_per_month',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='schedule_in',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='schedule_out',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='service_incentive_leave',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sick_leave',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='solo_parent_leave',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='vacation_leave',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='vawc_leave',
        ),
    ]
