# Generated by Django 3.2.25 on 2026-05-05 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_auto_20260505_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
