# Generated by Django 3.2.25 on 2026-05-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_userprofile_admin_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logs',
            field=models.BooleanField(default=False),
        ),
    ]
