# Generated by Django 3.2.25 on 2026-05-29 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0014_documentfile_group_viewer'),
        ('User', '0018_groupuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='MainGroup',
        ),
    ]
