# Generated by Django 3.2.25 on 2026-05-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_rename_group_maingroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
