# Generated by Django 3.2.25 on 2026-06-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_alter_groupuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maingroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
