# Generated by Django 3.2.25 on 2026-06-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_alter_maingroup_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupEmail',
        ),
    ]
